[package]
name = "vita_virtual_device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
derive_builder = "0.12.0"
rstar = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.183", features = ["serde_derive"] }
thiserror = "1.0.38"
vita_reports = { version = "0.1.0", path = "../vita_reports" }

[target.'cfg(target_os = "linux")'.dependencies]
input-linux = "0.6.0"

[target.'cfg(windows)'.dependencies]
vigem-client = { git = "https://github.com/musikid/vigem-client.git", branch = "ds4_new_api" }
