name: Create release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.release.outputs.id }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1

  client:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    needs: create-release
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf make git-core cmake python3

      - uses: actions/checkout@v3
        with:
          repository: google/flatbuffers
          path: flatbuffers

      - name: Install flatc
        run: |
          cmake -B build -S flatbuffers
          cmake --install build

      - name: install frontend dependencies
        run: cd client/packages/gui && pnpm install

      - uses: tauri-apps/tauri-action@v0
        with:
          projectPath: client/packages/gui
          releaseId: ${{ needs.create-release.outputs.release_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  server:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v2

      - name: Install flatc
        run: |
          sudo apt-get update
          sudo apt-get install -y make git-core cmake python3
          git clone https://github.com/google/flatbuffers.git
          cd flatbuffers
          cmake -G "Unix Makefiles"
          make -j
          sudo make install

      - name: Install VitaSDK
        run: |
          echo "VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          export VITASDK=/usr/local/vitasdk
          ./bootstrap-vitasdk.sh
          ./install-all.sh

      - name: Install flatbuffers
        run: |
          sudo apt-get install -y libarchive-tools xutils-dev
          git clone https://github.com/musikid/packages
          cd packages/flatbuffers
          export PATH="$VITASDK/bin:$PATH" 
          vita-makepkg -C -f -d -i

      - name: Build
        run: |
          cmake -S server -B build -D CMAKE_BUILD_TYPE=Release
          cmake --build build
      
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/VitaPad.vpk
          
